[phases.setup]
nixPkgs = ["nodejs_22", "npm"]

[phases.install]
cmds = ["cd client && npm ci", "cd server && npm ci"]

[phases.build]
cmds = ["cd client && npm run build"]

[start]
cmd = "cd server && node seed.js; node index.js"
